### ISSUE TITLE
versioneer not working with conda packge

### ISSUE THREAD

**Issue by AlbertDeFusco** [AlbertDeFusco/tranquilizer#17]
`__version__` is not correct

**Comment by msarahan** [comment]
How did you set up versioneer? The conda package cookiecutter was missing something for a while. https://github.com/conda/conda-package-handling/blob/master/.gitattributes

**Comment by AlbertDeFusco** [comment]
Ah, I'll take a look at that. I may have just copied some files from another repo.

I discovered that the package on my channel `defusco` reports the correct `__version__`, but the conda-forge package does not. There could be a problem with my feedstock.

**Comment by AlbertDeFusco** [comment]
fixed in 0.4.1

I forgot the include `MANIFEST.in`, which meant that `versioneer.py` was not added in all the right places. I also changed the feedstock recipe url to pypi.
