### ISSUE TITLE
Use standard types

### ISSUE THREAD

**Issue by mrocklin** [AlbertDeFusco/tranquilizer#4]
In this example we see that tranqilizer can automatically convert values into common types:

```python
from tranquilizer import tranquilize
from tranquilizer.types import ParsedDateTime, TypedList

@tranquilize(method='post')
def convert(string: str, date: ParsedDateTime, items: TypedList[float], factor: int = 10):
    '''Let's convert strings to something useful'''
```

However, this seems to require the use of specialized types defined within tranquilizer.   I suspect that this feature would see more use if it supported standard Python types instead.  These are already likely to be used within existing code, and so doesn't force the user to buy into tranquilizer as heavily.

```python
from datetime import date
from typing import List
from tranquilizer import tranquilize

@tranquilize(method='post')
def convert(string: str, date: date, items: List[float], factor: int = 10):
    '''Let's convert strings to something useful'''
```

Presumably this would require tranquilize to map between standard types and its own operations.  I haven't looked at the codebase, so I'm not sure how challenging this would be. 

Just a thought, feel free to close and disregard.

**Comment by AlbertDeFusco** [comment]
Thanks for the suggestion. Version 0.1.0 now supports standard types and no longer exposes the special type classes it needs to perform the parsing.
